version: "3.6"
services: 
  selenium: 
    image: "selenium/hub"
    container_name: "conclave-selenium"
    ports: 
      - 4444:4444
      - 4443:4443
      - 4442:4442
    environment:
      GRID_MAX_SESSION: 10
  chrome:
    image: "selenium/node-chrome"
    deploy:
      replicas: 4
    depends_on:
      - selenium
    environment:
      SE_EVENT_BUS_HOST: "conclave-selenium"
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_GRID_URL: "http://localhost:4444"
    